/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionsCacheListActionsCachesInner from './ActionsCacheListActionsCachesInner';

/**
 * The ActionsCacheList model module.
 * @module model/ActionsCacheList
 * @version 1.1.4
 */
class ActionsCacheList {
    /**
     * Constructs a new <code>ActionsCacheList</code>.
     * Repository actions caches
     * @alias module:model/ActionsCacheList
     * @param totalCount {Number} Total number of caches
     * @param actionsCaches {Array.<module:model/ActionsCacheListActionsCachesInner>} Array of caches
     */
    constructor(totalCount, actionsCaches) { 
        
        ActionsCacheList.initialize(this, totalCount, actionsCaches);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, totalCount, actionsCaches) { 
        obj['total_count'] = totalCount;
        obj['actions_caches'] = actionsCaches;
    }

    /**
     * Constructs a <code>ActionsCacheList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionsCacheList} obj Optional instance to populate.
     * @return {module:model/ActionsCacheList} The populated <code>ActionsCacheList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionsCacheList();

            if (data.hasOwnProperty('total_count')) {
                obj['total_count'] = ApiClient.convertToType(data['total_count'], 'Number');
            }
            if (data.hasOwnProperty('actions_caches')) {
                obj['actions_caches'] = ApiClient.convertToType(data['actions_caches'], [ActionsCacheListActionsCachesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ActionsCacheList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ActionsCacheList</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ActionsCacheList.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['actions_caches']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['actions_caches'])) {
                throw new Error("Expected the field `actions_caches` to be an array in the JSON data but got " + data['actions_caches']);
            }
            // validate the optional field `actions_caches` (array)
            for (const item of data['actions_caches']) {
                ActionsCacheListActionsCachesInner.validateJSON(item);
            };
        }

        return true;
    }


}

ActionsCacheList.RequiredProperties = ["total_count", "actions_caches"];

/**
 * Total number of caches
 * @member {Number} total_count
 */
ActionsCacheList.prototype['total_count'] = undefined;

/**
 * Array of caches
 * @member {Array.<module:model/ActionsCacheListActionsCachesInner>} actions_caches
 */
ActionsCacheList.prototype['actions_caches'] = undefined;






export default ActionsCacheList;

