/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RunnerLabel from './RunnerLabel';

/**
 * The ActionsListLabelsForSelfHostedRunnerForOrg200Response model module.
 * @module model/ActionsListLabelsForSelfHostedRunnerForOrg200Response
 * @version 1.1.4
 */
class ActionsListLabelsForSelfHostedRunnerForOrg200Response {
    /**
     * Constructs a new <code>ActionsListLabelsForSelfHostedRunnerForOrg200Response</code>.
     * @alias module:model/ActionsListLabelsForSelfHostedRunnerForOrg200Response
     * @param totalCount {Number} 
     * @param labels {Array.<module:model/RunnerLabel>} 
     */
    constructor(totalCount, labels) { 
        
        ActionsListLabelsForSelfHostedRunnerForOrg200Response.initialize(this, totalCount, labels);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, totalCount, labels) { 
        obj['total_count'] = totalCount;
        obj['labels'] = labels;
    }

    /**
     * Constructs a <code>ActionsListLabelsForSelfHostedRunnerForOrg200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionsListLabelsForSelfHostedRunnerForOrg200Response} obj Optional instance to populate.
     * @return {module:model/ActionsListLabelsForSelfHostedRunnerForOrg200Response} The populated <code>ActionsListLabelsForSelfHostedRunnerForOrg200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionsListLabelsForSelfHostedRunnerForOrg200Response();

            if (data.hasOwnProperty('total_count')) {
                obj['total_count'] = ApiClient.convertToType(data['total_count'], 'Number');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], [RunnerLabel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ActionsListLabelsForSelfHostedRunnerForOrg200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ActionsListLabelsForSelfHostedRunnerForOrg200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ActionsListLabelsForSelfHostedRunnerForOrg200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['labels']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['labels'])) {
                throw new Error("Expected the field `labels` to be an array in the JSON data but got " + data['labels']);
            }
            // validate the optional field `labels` (array)
            for (const item of data['labels']) {
                RunnerLabel.validateJSON(item);
            };
        }

        return true;
    }


}

ActionsListLabelsForSelfHostedRunnerForOrg200Response.RequiredProperties = ["total_count", "labels"];

/**
 * @member {Number} total_count
 */
ActionsListLabelsForSelfHostedRunnerForOrg200Response.prototype['total_count'] = undefined;

/**
 * @member {Array.<module:model/RunnerLabel>} labels
 */
ActionsListLabelsForSelfHostedRunnerForOrg200Response.prototype['labels'] = undefined;






export default ActionsListLabelsForSelfHostedRunnerForOrg200Response;

