/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BranchProtectionRequiredLinearHistory model module.
 * @module model/BranchProtectionRequiredLinearHistory
 * @version 1.1.4
 */
class BranchProtectionRequiredLinearHistory {
    /**
     * Constructs a new <code>BranchProtectionRequiredLinearHistory</code>.
     * @alias module:model/BranchProtectionRequiredLinearHistory
     */
    constructor() { 
        
        BranchProtectionRequiredLinearHistory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BranchProtectionRequiredLinearHistory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BranchProtectionRequiredLinearHistory} obj Optional instance to populate.
     * @return {module:model/BranchProtectionRequiredLinearHistory} The populated <code>BranchProtectionRequiredLinearHistory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BranchProtectionRequiredLinearHistory();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BranchProtectionRequiredLinearHistory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BranchProtectionRequiredLinearHistory</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} enabled
 */
BranchProtectionRequiredLinearHistory.prototype['enabled'] = undefined;






export default BranchProtectionRequiredLinearHistory;

