/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BranchShortCommit from './BranchShortCommit';

/**
 * The BranchShort model module.
 * @module model/BranchShort
 * @version 1.1.4
 */
class BranchShort {
    /**
     * Constructs a new <code>BranchShort</code>.
     * Branch Short
     * @alias module:model/BranchShort
     * @param name {String} 
     * @param commit {module:model/BranchShortCommit} 
     * @param _protected {Boolean} 
     */
    constructor(name, commit, _protected) { 
        
        BranchShort.initialize(this, name, commit, _protected);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, commit, _protected) { 
        obj['name'] = name;
        obj['commit'] = commit;
        obj['protected'] = _protected;
    }

    /**
     * Constructs a <code>BranchShort</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BranchShort} obj Optional instance to populate.
     * @return {module:model/BranchShort} The populated <code>BranchShort</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BranchShort();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('commit')) {
                obj['commit'] = BranchShortCommit.constructFromObject(data['commit']);
            }
            if (data.hasOwnProperty('protected')) {
                obj['protected'] = ApiClient.convertToType(data['protected'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BranchShort</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BranchShort</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BranchShort.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `commit`
        if (data['commit']) { // data not null
          BranchShortCommit.validateJSON(data['commit']);
        }

        return true;
    }


}

BranchShort.RequiredProperties = ["name", "commit", "protected"];

/**
 * @member {String} name
 */
BranchShort.prototype['name'] = undefined;

/**
 * @member {module:model/BranchShortCommit} commit
 */
BranchShort.prototype['commit'] = undefined;

/**
 * @member {Boolean} protected
 */
BranchShort.prototype['protected'] = undefined;






export default BranchShort;

