/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CommitSearchResultItemCommitAuthor model module.
 * @module model/CommitSearchResultItemCommitAuthor
 * @version 1.1.4
 */
class CommitSearchResultItemCommitAuthor {
    /**
     * Constructs a new <code>CommitSearchResultItemCommitAuthor</code>.
     * @alias module:model/CommitSearchResultItemCommitAuthor
     * @param name {String} 
     * @param email {String} 
     * @param date {Date} 
     */
    constructor(name, email, date) { 
        
        CommitSearchResultItemCommitAuthor.initialize(this, name, email, date);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, email, date) { 
        obj['name'] = name;
        obj['email'] = email;
        obj['date'] = date;
    }

    /**
     * Constructs a <code>CommitSearchResultItemCommitAuthor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CommitSearchResultItemCommitAuthor} obj Optional instance to populate.
     * @return {module:model/CommitSearchResultItemCommitAuthor} The populated <code>CommitSearchResultItemCommitAuthor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommitSearchResultItemCommitAuthor();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CommitSearchResultItemCommitAuthor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CommitSearchResultItemCommitAuthor</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CommitSearchResultItemCommitAuthor.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}

CommitSearchResultItemCommitAuthor.RequiredProperties = ["name", "email", "date"];

/**
 * @member {String} name
 */
CommitSearchResultItemCommitAuthor.prototype['name'] = undefined;

/**
 * @member {String} email
 */
CommitSearchResultItemCommitAuthor.prototype['email'] = undefined;

/**
 * @member {Date} date
 */
CommitSearchResultItemCommitAuthor.prototype['date'] = undefined;






export default CommitSearchResultItemCommitAuthor;

