/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeploymentBranchPolicyNamePatternWithType model module.
 * @module model/DeploymentBranchPolicyNamePatternWithType
 * @version 1.1.4
 */
class DeploymentBranchPolicyNamePatternWithType {
    /**
     * Constructs a new <code>DeploymentBranchPolicyNamePatternWithType</code>.
     * @alias module:model/DeploymentBranchPolicyNamePatternWithType
     * @param name {String} The name pattern that branches or tags must match in order to deploy to the environment.  Wildcard characters will not match `/`. For example, to match branches that begin with `release/` and contain an additional single slash, use `release/_*_/_*`. For more information about pattern matching syntax, see the [Ruby File.fnmatch documentation](https://ruby-doc.org/core-2.5.1/File.html#method-c-fnmatch).
     */
    constructor(name) { 
        
        DeploymentBranchPolicyNamePatternWithType.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>DeploymentBranchPolicyNamePatternWithType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeploymentBranchPolicyNamePatternWithType} obj Optional instance to populate.
     * @return {module:model/DeploymentBranchPolicyNamePatternWithType} The populated <code>DeploymentBranchPolicyNamePatternWithType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeploymentBranchPolicyNamePatternWithType();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeploymentBranchPolicyNamePatternWithType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeploymentBranchPolicyNamePatternWithType</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeploymentBranchPolicyNamePatternWithType.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

DeploymentBranchPolicyNamePatternWithType.RequiredProperties = ["name"];

/**
 * The name pattern that branches or tags must match in order to deploy to the environment.  Wildcard characters will not match `/`. For example, to match branches that begin with `release/` and contain an additional single slash, use `release/_*_/_*`. For more information about pattern matching syntax, see the [Ruby File.fnmatch documentation](https://ruby-doc.org/core-2.5.1/File.html#method-c-fnmatch).
 * @member {String} name
 */
DeploymentBranchPolicyNamePatternWithType.prototype['name'] = undefined;

/**
 * Whether this rule targets a branch or tag
 * @member {module:model/DeploymentBranchPolicyNamePatternWithType.TypeEnum} type
 */
DeploymentBranchPolicyNamePatternWithType.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
DeploymentBranchPolicyNamePatternWithType['TypeEnum'] = {

    /**
     * value: "branch"
     * @const
     */
    "branch": "branch",

    /**
     * value: "tag"
     * @const
     */
    "tag": "tag"
};



export default DeploymentBranchPolicyNamePatternWithType;

