/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NullableIntegration from './NullableIntegration';

/**
 * The DeploymentSimple model module.
 * @module model/DeploymentSimple
 * @version 1.1.4
 */
class DeploymentSimple {
    /**
     * Constructs a new <code>DeploymentSimple</code>.
     * A deployment created as the result of an Actions check run from a workflow that references an environment
     * @alias module:model/DeploymentSimple
     * @param url {String} 
     * @param id {Number} Unique identifier of the deployment
     * @param nodeId {String} 
     * @param task {String} Parameter to specify a task to execute
     * @param environment {String} Name for the target deployment environment.
     * @param description {String} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     * @param statusesUrl {String} 
     * @param repositoryUrl {String} 
     */
    constructor(url, id, nodeId, task, environment, description, createdAt, updatedAt, statusesUrl, repositoryUrl) { 
        
        DeploymentSimple.initialize(this, url, id, nodeId, task, environment, description, createdAt, updatedAt, statusesUrl, repositoryUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, id, nodeId, task, environment, description, createdAt, updatedAt, statusesUrl, repositoryUrl) { 
        obj['url'] = url;
        obj['id'] = id;
        obj['node_id'] = nodeId;
        obj['task'] = task;
        obj['environment'] = environment;
        obj['description'] = description;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
        obj['statuses_url'] = statusesUrl;
        obj['repository_url'] = repositoryUrl;
    }

    /**
     * Constructs a <code>DeploymentSimple</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeploymentSimple} obj Optional instance to populate.
     * @return {module:model/DeploymentSimple} The populated <code>DeploymentSimple</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeploymentSimple();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('node_id')) {
                obj['node_id'] = ApiClient.convertToType(data['node_id'], 'String');
            }
            if (data.hasOwnProperty('task')) {
                obj['task'] = ApiClient.convertToType(data['task'], 'String');
            }
            if (data.hasOwnProperty('original_environment')) {
                obj['original_environment'] = ApiClient.convertToType(data['original_environment'], 'String');
            }
            if (data.hasOwnProperty('environment')) {
                obj['environment'] = ApiClient.convertToType(data['environment'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('statuses_url')) {
                obj['statuses_url'] = ApiClient.convertToType(data['statuses_url'], 'String');
            }
            if (data.hasOwnProperty('repository_url')) {
                obj['repository_url'] = ApiClient.convertToType(data['repository_url'], 'String');
            }
            if (data.hasOwnProperty('transient_environment')) {
                obj['transient_environment'] = ApiClient.convertToType(data['transient_environment'], 'Boolean');
            }
            if (data.hasOwnProperty('production_environment')) {
                obj['production_environment'] = ApiClient.convertToType(data['production_environment'], 'Boolean');
            }
            if (data.hasOwnProperty('performed_via_github_app')) {
                obj['performed_via_github_app'] = NullableIntegration.constructFromObject(data['performed_via_github_app']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeploymentSimple</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeploymentSimple</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeploymentSimple.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['node_id'] && !(typeof data['node_id'] === 'string' || data['node_id'] instanceof String)) {
            throw new Error("Expected the field `node_id` to be a primitive type in the JSON string but got " + data['node_id']);
        }
        // ensure the json data is a string
        if (data['task'] && !(typeof data['task'] === 'string' || data['task'] instanceof String)) {
            throw new Error("Expected the field `task` to be a primitive type in the JSON string but got " + data['task']);
        }
        // ensure the json data is a string
        if (data['original_environment'] && !(typeof data['original_environment'] === 'string' || data['original_environment'] instanceof String)) {
            throw new Error("Expected the field `original_environment` to be a primitive type in the JSON string but got " + data['original_environment']);
        }
        // ensure the json data is a string
        if (data['environment'] && !(typeof data['environment'] === 'string' || data['environment'] instanceof String)) {
            throw new Error("Expected the field `environment` to be a primitive type in the JSON string but got " + data['environment']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['statuses_url'] && !(typeof data['statuses_url'] === 'string' || data['statuses_url'] instanceof String)) {
            throw new Error("Expected the field `statuses_url` to be a primitive type in the JSON string but got " + data['statuses_url']);
        }
        // ensure the json data is a string
        if (data['repository_url'] && !(typeof data['repository_url'] === 'string' || data['repository_url'] instanceof String)) {
            throw new Error("Expected the field `repository_url` to be a primitive type in the JSON string but got " + data['repository_url']);
        }
        // validate the optional field `performed_via_github_app`
        if (data['performed_via_github_app']) { // data not null
          NullableIntegration.validateJSON(data['performed_via_github_app']);
        }

        return true;
    }


}

DeploymentSimple.RequiredProperties = ["url", "id", "node_id", "task", "environment", "description", "created_at", "updated_at", "statuses_url", "repository_url"];

/**
 * @member {String} url
 */
DeploymentSimple.prototype['url'] = undefined;

/**
 * Unique identifier of the deployment
 * @member {Number} id
 */
DeploymentSimple.prototype['id'] = undefined;

/**
 * @member {String} node_id
 */
DeploymentSimple.prototype['node_id'] = undefined;

/**
 * Parameter to specify a task to execute
 * @member {String} task
 */
DeploymentSimple.prototype['task'] = undefined;

/**
 * @member {String} original_environment
 */
DeploymentSimple.prototype['original_environment'] = undefined;

/**
 * Name for the target deployment environment.
 * @member {String} environment
 */
DeploymentSimple.prototype['environment'] = undefined;

/**
 * @member {String} description
 */
DeploymentSimple.prototype['description'] = undefined;

/**
 * @member {Date} created_at
 */
DeploymentSimple.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
DeploymentSimple.prototype['updated_at'] = undefined;

/**
 * @member {String} statuses_url
 */
DeploymentSimple.prototype['statuses_url'] = undefined;

/**
 * @member {String} repository_url
 */
DeploymentSimple.prototype['repository_url'] = undefined;

/**
 * Specifies if the given environment is will no longer exist at some point in the future. Default: false.
 * @member {Boolean} transient_environment
 */
DeploymentSimple.prototype['transient_environment'] = undefined;

/**
 * Specifies if the given environment is one that end-users directly interact with. Default: false.
 * @member {Boolean} production_environment
 */
DeploymentSimple.prototype['production_environment'] = undefined;

/**
 * @member {module:model/NullableIntegration} performed_via_github_app
 */
DeploymentSimple.prototype['performed_via_github_app'] = undefined;






export default DeploymentSimple;

