/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MigrationsUpdateImportRequest model module.
 * @module model/MigrationsUpdateImportRequest
 * @version 1.1.4
 */
class MigrationsUpdateImportRequest {
    /**
     * Constructs a new <code>MigrationsUpdateImportRequest</code>.
     * @alias module:model/MigrationsUpdateImportRequest
     */
    constructor() { 
        
        MigrationsUpdateImportRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MigrationsUpdateImportRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MigrationsUpdateImportRequest} obj Optional instance to populate.
     * @return {module:model/MigrationsUpdateImportRequest} The populated <code>MigrationsUpdateImportRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MigrationsUpdateImportRequest();

            if (data.hasOwnProperty('vcs_username')) {
                obj['vcs_username'] = ApiClient.convertToType(data['vcs_username'], 'String');
            }
            if (data.hasOwnProperty('vcs_password')) {
                obj['vcs_password'] = ApiClient.convertToType(data['vcs_password'], 'String');
            }
            if (data.hasOwnProperty('vcs')) {
                obj['vcs'] = ApiClient.convertToType(data['vcs'], 'String');
            }
            if (data.hasOwnProperty('tfvc_project')) {
                obj['tfvc_project'] = ApiClient.convertToType(data['tfvc_project'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MigrationsUpdateImportRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MigrationsUpdateImportRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['vcs_username'] && !(typeof data['vcs_username'] === 'string' || data['vcs_username'] instanceof String)) {
            throw new Error("Expected the field `vcs_username` to be a primitive type in the JSON string but got " + data['vcs_username']);
        }
        // ensure the json data is a string
        if (data['vcs_password'] && !(typeof data['vcs_password'] === 'string' || data['vcs_password'] instanceof String)) {
            throw new Error("Expected the field `vcs_password` to be a primitive type in the JSON string but got " + data['vcs_password']);
        }
        // ensure the json data is a string
        if (data['vcs'] && !(typeof data['vcs'] === 'string' || data['vcs'] instanceof String)) {
            throw new Error("Expected the field `vcs` to be a primitive type in the JSON string but got " + data['vcs']);
        }
        // ensure the json data is a string
        if (data['tfvc_project'] && !(typeof data['tfvc_project'] === 'string' || data['tfvc_project'] instanceof String)) {
            throw new Error("Expected the field `tfvc_project` to be a primitive type in the JSON string but got " + data['tfvc_project']);
        }

        return true;
    }


}



/**
 * The username to provide to the originating repository.
 * @member {String} vcs_username
 */
MigrationsUpdateImportRequest.prototype['vcs_username'] = undefined;

/**
 * The password to provide to the originating repository.
 * @member {String} vcs_password
 */
MigrationsUpdateImportRequest.prototype['vcs_password'] = undefined;

/**
 * The type of version control system you are migrating from.
 * @member {module:model/MigrationsUpdateImportRequest.VcsEnum} vcs
 */
MigrationsUpdateImportRequest.prototype['vcs'] = undefined;

/**
 * For a tfvc import, the name of the project that is being imported.
 * @member {String} tfvc_project
 */
MigrationsUpdateImportRequest.prototype['tfvc_project'] = undefined;





/**
 * Allowed values for the <code>vcs</code> property.
 * @enum {String}
 * @readonly
 */
MigrationsUpdateImportRequest['VcsEnum'] = {

    /**
     * value: "subversion"
     * @const
     */
    "subversion": "subversion",

    /**
     * value: "tfvc"
     * @const
     */
    "tfvc": "tfvc",

    /**
     * value: "git"
     * @const
     */
    "git": "git",

    /**
     * value: "mercurial"
     * @const
     */
    "mercurial": "mercurial"
};



export default MigrationsUpdateImportRequest;

