/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MigrationsMapCommitAuthorRequest model module.
 * @module model/MigrationsMapCommitAuthorRequest
 * @version 1.1.4
 */
class MigrationsMapCommitAuthorRequest {
    /**
     * Constructs a new <code>MigrationsMapCommitAuthorRequest</code>.
     * @alias module:model/MigrationsMapCommitAuthorRequest
     */
    constructor() { 
        
        MigrationsMapCommitAuthorRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MigrationsMapCommitAuthorRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MigrationsMapCommitAuthorRequest} obj Optional instance to populate.
     * @return {module:model/MigrationsMapCommitAuthorRequest} The populated <code>MigrationsMapCommitAuthorRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MigrationsMapCommitAuthorRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MigrationsMapCommitAuthorRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MigrationsMapCommitAuthorRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * The new Git author email.
 * @member {String} email
 */
MigrationsMapCommitAuthorRequest.prototype['email'] = undefined;

/**
 * The new Git author name.
 * @member {String} name
 */
MigrationsMapCommitAuthorRequest.prototype['name'] = undefined;






export default MigrationsMapCommitAuthorRequest;

