/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PagesDeploymentStatus model module.
 * @module model/PagesDeploymentStatus
 * @version 1.1.4
 */
class PagesDeploymentStatus {
    /**
     * Constructs a new <code>PagesDeploymentStatus</code>.
     * @alias module:model/PagesDeploymentStatus
     */
    constructor() { 
        
        PagesDeploymentStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PagesDeploymentStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PagesDeploymentStatus} obj Optional instance to populate.
     * @return {module:model/PagesDeploymentStatus} The populated <code>PagesDeploymentStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PagesDeploymentStatus();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PagesDeploymentStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PagesDeploymentStatus</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * The current status of the deployment.
 * @member {module:model/PagesDeploymentStatus.StatusEnum} status
 */
PagesDeploymentStatus.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
PagesDeploymentStatus['StatusEnum'] = {

    /**
     * value: "deployment_in_progress"
     * @const
     */
    "deployment_in_progress": "deployment_in_progress",

    /**
     * value: "syncing_files"
     * @const
     */
    "syncing_files": "syncing_files",

    /**
     * value: "finished_file_sync"
     * @const
     */
    "finished_file_sync": "finished_file_sync",

    /**
     * value: "updating_pages"
     * @const
     */
    "updating_pages": "updating_pages",

    /**
     * value: "purging_cdn"
     * @const
     */
    "purging_cdn": "purging_cdn",

    /**
     * value: "deployment_cancelled"
     * @const
     */
    "deployment_cancelled": "deployment_cancelled",

    /**
     * value: "deployment_failed"
     * @const
     */
    "deployment_failed": "deployment_failed",

    /**
     * value: "deployment_content_failed"
     * @const
     */
    "deployment_content_failed": "deployment_content_failed",

    /**
     * value: "deployment_attempt_error"
     * @const
     */
    "deployment_attempt_error": "deployment_attempt_error",

    /**
     * value: "deployment_lost"
     * @const
     */
    "deployment_lost": "deployment_lost",

    /**
     * value: "succeed"
     * @const
     */
    "succeed": "succeed"
};



export default PagesDeploymentStatus;

