/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PorterAuthor model module.
 * @module model/PorterAuthor
 * @version 1.1.4
 */
class PorterAuthor {
    /**
     * Constructs a new <code>PorterAuthor</code>.
     * Porter Author
     * @alias module:model/PorterAuthor
     * @param id {Number} 
     * @param remoteId {String} 
     * @param remoteName {String} 
     * @param email {String} 
     * @param name {String} 
     * @param url {String} 
     * @param importUrl {String} 
     */
    constructor(id, remoteId, remoteName, email, name, url, importUrl) { 
        
        PorterAuthor.initialize(this, id, remoteId, remoteName, email, name, url, importUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, remoteId, remoteName, email, name, url, importUrl) { 
        obj['id'] = id;
        obj['remote_id'] = remoteId;
        obj['remote_name'] = remoteName;
        obj['email'] = email;
        obj['name'] = name;
        obj['url'] = url;
        obj['import_url'] = importUrl;
    }

    /**
     * Constructs a <code>PorterAuthor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PorterAuthor} obj Optional instance to populate.
     * @return {module:model/PorterAuthor} The populated <code>PorterAuthor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PorterAuthor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('remote_id')) {
                obj['remote_id'] = ApiClient.convertToType(data['remote_id'], 'String');
            }
            if (data.hasOwnProperty('remote_name')) {
                obj['remote_name'] = ApiClient.convertToType(data['remote_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('import_url')) {
                obj['import_url'] = ApiClient.convertToType(data['import_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PorterAuthor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PorterAuthor</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PorterAuthor.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['remote_id'] && !(typeof data['remote_id'] === 'string' || data['remote_id'] instanceof String)) {
            throw new Error("Expected the field `remote_id` to be a primitive type in the JSON string but got " + data['remote_id']);
        }
        // ensure the json data is a string
        if (data['remote_name'] && !(typeof data['remote_name'] === 'string' || data['remote_name'] instanceof String)) {
            throw new Error("Expected the field `remote_name` to be a primitive type in the JSON string but got " + data['remote_name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['import_url'] && !(typeof data['import_url'] === 'string' || data['import_url'] instanceof String)) {
            throw new Error("Expected the field `import_url` to be a primitive type in the JSON string but got " + data['import_url']);
        }

        return true;
    }


}

PorterAuthor.RequiredProperties = ["id", "remote_id", "remote_name", "email", "name", "url", "import_url"];

/**
 * @member {Number} id
 */
PorterAuthor.prototype['id'] = undefined;

/**
 * @member {String} remote_id
 */
PorterAuthor.prototype['remote_id'] = undefined;

/**
 * @member {String} remote_name
 */
PorterAuthor.prototype['remote_name'] = undefined;

/**
 * @member {String} email
 */
PorterAuthor.prototype['email'] = undefined;

/**
 * @member {String} name
 */
PorterAuthor.prototype['name'] = undefined;

/**
 * @member {String} url
 */
PorterAuthor.prototype['url'] = undefined;

/**
 * @member {String} import_url
 */
PorterAuthor.prototype['import_url'] = undefined;






export default PorterAuthor;

