/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReposCreatePagesDeploymentRequest model module.
 * @module model/ReposCreatePagesDeploymentRequest
 * @version 1.1.4
 */
class ReposCreatePagesDeploymentRequest {
    /**
     * Constructs a new <code>ReposCreatePagesDeploymentRequest</code>.
     * The object used to create GitHub Pages deployment
     * @alias module:model/ReposCreatePagesDeploymentRequest
     * @param pagesBuildVersion {String} A unique string that represents the version of the build for this deployment.
     * @param oidcToken {String} The OIDC token issued by GitHub Actions certifying the origin of the deployment.
     */
    constructor(pagesBuildVersion, oidcToken) { 
        
        ReposCreatePagesDeploymentRequest.initialize(this, pagesBuildVersion, oidcToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pagesBuildVersion, oidcToken) { 
        obj['pages_build_version'] = pagesBuildVersion || 'GITHUB_SHA';
        obj['oidc_token'] = oidcToken;
    }

    /**
     * Constructs a <code>ReposCreatePagesDeploymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReposCreatePagesDeploymentRequest} obj Optional instance to populate.
     * @return {module:model/ReposCreatePagesDeploymentRequest} The populated <code>ReposCreatePagesDeploymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReposCreatePagesDeploymentRequest();

            if (data.hasOwnProperty('artifact_id')) {
                obj['artifact_id'] = ApiClient.convertToType(data['artifact_id'], 'Number');
            }
            if (data.hasOwnProperty('artifact_url')) {
                obj['artifact_url'] = ApiClient.convertToType(data['artifact_url'], 'String');
            }
            if (data.hasOwnProperty('environment')) {
                obj['environment'] = ApiClient.convertToType(data['environment'], 'String');
            }
            if (data.hasOwnProperty('pages_build_version')) {
                obj['pages_build_version'] = ApiClient.convertToType(data['pages_build_version'], 'String');
            }
            if (data.hasOwnProperty('oidc_token')) {
                obj['oidc_token'] = ApiClient.convertToType(data['oidc_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReposCreatePagesDeploymentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReposCreatePagesDeploymentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReposCreatePagesDeploymentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['artifact_url'] && !(typeof data['artifact_url'] === 'string' || data['artifact_url'] instanceof String)) {
            throw new Error("Expected the field `artifact_url` to be a primitive type in the JSON string but got " + data['artifact_url']);
        }
        // ensure the json data is a string
        if (data['environment'] && !(typeof data['environment'] === 'string' || data['environment'] instanceof String)) {
            throw new Error("Expected the field `environment` to be a primitive type in the JSON string but got " + data['environment']);
        }
        // ensure the json data is a string
        if (data['pages_build_version'] && !(typeof data['pages_build_version'] === 'string' || data['pages_build_version'] instanceof String)) {
            throw new Error("Expected the field `pages_build_version` to be a primitive type in the JSON string but got " + data['pages_build_version']);
        }
        // ensure the json data is a string
        if (data['oidc_token'] && !(typeof data['oidc_token'] === 'string' || data['oidc_token'] instanceof String)) {
            throw new Error("Expected the field `oidc_token` to be a primitive type in the JSON string but got " + data['oidc_token']);
        }

        return true;
    }


}

ReposCreatePagesDeploymentRequest.RequiredProperties = ["pages_build_version", "oidc_token"];

/**
 * The ID of an artifact that contains the .zip or .tar of static assets to deploy. The artifact belongs to the repository. Either `artifact_id` or `artifact_url` are required.
 * @member {Number} artifact_id
 */
ReposCreatePagesDeploymentRequest.prototype['artifact_id'] = undefined;

/**
 * The URL of an artifact that contains the .zip or .tar of static assets to deploy. The artifact belongs to the repository. Either `artifact_id` or `artifact_url` are required.
 * @member {String} artifact_url
 */
ReposCreatePagesDeploymentRequest.prototype['artifact_url'] = undefined;

/**
 * The target environment for this GitHub Pages deployment.
 * @member {String} environment
 * @default 'github-pages'
 */
ReposCreatePagesDeploymentRequest.prototype['environment'] = 'github-pages';

/**
 * A unique string that represents the version of the build for this deployment.
 * @member {String} pages_build_version
 * @default 'GITHUB_SHA'
 */
ReposCreatePagesDeploymentRequest.prototype['pages_build_version'] = 'GITHUB_SHA';

/**
 * The OIDC token issued by GitHub Actions certifying the origin of the deployment.
 * @member {String} oidc_token
 */
ReposCreatePagesDeploymentRequest.prototype['oidc_token'] = undefined;






export default ReposCreatePagesDeploymentRequest;

