/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SecretScanningLocationDiscussionTitle model module.
 * @module model/SecretScanningLocationDiscussionTitle
 * @version 1.1.4
 */
class SecretScanningLocationDiscussionTitle {
    /**
     * Constructs a new <code>SecretScanningLocationDiscussionTitle</code>.
     * Represents a &#39;discussion_title&#39; secret scanning location type. This location type shows that a secret was detected in the title of a discussion.
     * @alias module:model/SecretScanningLocationDiscussionTitle
     * @param discussionTitleUrl {String} The URL to the discussion where the secret was detected.
     */
    constructor(discussionTitleUrl) { 
        
        SecretScanningLocationDiscussionTitle.initialize(this, discussionTitleUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, discussionTitleUrl) { 
        obj['discussion_title_url'] = discussionTitleUrl;
    }

    /**
     * Constructs a <code>SecretScanningLocationDiscussionTitle</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecretScanningLocationDiscussionTitle} obj Optional instance to populate.
     * @return {module:model/SecretScanningLocationDiscussionTitle} The populated <code>SecretScanningLocationDiscussionTitle</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecretScanningLocationDiscussionTitle();

            if (data.hasOwnProperty('discussion_title_url')) {
                obj['discussion_title_url'] = ApiClient.convertToType(data['discussion_title_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SecretScanningLocationDiscussionTitle</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SecretScanningLocationDiscussionTitle</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SecretScanningLocationDiscussionTitle.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['discussion_title_url'] && !(typeof data['discussion_title_url'] === 'string' || data['discussion_title_url'] instanceof String)) {
            throw new Error("Expected the field `discussion_title_url` to be a primitive type in the JSON string but got " + data['discussion_title_url']);
        }

        return true;
    }


}

SecretScanningLocationDiscussionTitle.RequiredProperties = ["discussion_title_url"];

/**
 * The URL to the discussion where the secret was detected.
 * @member {String} discussion_title_url
 */
SecretScanningLocationDiscussionTitle.prototype['discussion_title_url'] = undefined;






export default SecretScanningLocationDiscussionTitle;

