/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SimpleClassroomUser model module.
 * @module model/SimpleClassroomUser
 * @version 1.1.4
 */
class SimpleClassroomUser {
    /**
     * Constructs a new <code>SimpleClassroomUser</code>.
     * A GitHub user simplified for Classroom.
     * @alias module:model/SimpleClassroomUser
     * @param id {Number} 
     * @param login {String} 
     * @param avatarUrl {String} 
     * @param htmlUrl {String} 
     */
    constructor(id, login, avatarUrl, htmlUrl) { 
        
        SimpleClassroomUser.initialize(this, id, login, avatarUrl, htmlUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, login, avatarUrl, htmlUrl) { 
        obj['id'] = id;
        obj['login'] = login;
        obj['avatar_url'] = avatarUrl;
        obj['html_url'] = htmlUrl;
    }

    /**
     * Constructs a <code>SimpleClassroomUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SimpleClassroomUser} obj Optional instance to populate.
     * @return {module:model/SimpleClassroomUser} The populated <code>SimpleClassroomUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimpleClassroomUser();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('avatar_url')) {
                obj['avatar_url'] = ApiClient.convertToType(data['avatar_url'], 'String');
            }
            if (data.hasOwnProperty('html_url')) {
                obj['html_url'] = ApiClient.convertToType(data['html_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SimpleClassroomUser</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SimpleClassroomUser</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SimpleClassroomUser.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['login'] && !(typeof data['login'] === 'string' || data['login'] instanceof String)) {
            throw new Error("Expected the field `login` to be a primitive type in the JSON string but got " + data['login']);
        }
        // ensure the json data is a string
        if (data['avatar_url'] && !(typeof data['avatar_url'] === 'string' || data['avatar_url'] instanceof String)) {
            throw new Error("Expected the field `avatar_url` to be a primitive type in the JSON string but got " + data['avatar_url']);
        }
        // ensure the json data is a string
        if (data['html_url'] && !(typeof data['html_url'] === 'string' || data['html_url'] instanceof String)) {
            throw new Error("Expected the field `html_url` to be a primitive type in the JSON string but got " + data['html_url']);
        }

        return true;
    }


}

SimpleClassroomUser.RequiredProperties = ["id", "login", "avatar_url", "html_url"];

/**
 * @member {Number} id
 */
SimpleClassroomUser.prototype['id'] = undefined;

/**
 * @member {String} login
 */
SimpleClassroomUser.prototype['login'] = undefined;

/**
 * @member {String} avatar_url
 */
SimpleClassroomUser.prototype['avatar_url'] = undefined;

/**
 * @member {String} html_url
 */
SimpleClassroomUser.prototype['html_url'] = undefined;






export default SimpleClassroomUser;

