/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TopicSearchResultItemRelatedInnerTopicRelation from './TopicSearchResultItemRelatedInnerTopicRelation';

/**
 * The TopicSearchResultItemRelatedInner model module.
 * @module model/TopicSearchResultItemRelatedInner
 * @version 1.1.4
 */
class TopicSearchResultItemRelatedInner {
    /**
     * Constructs a new <code>TopicSearchResultItemRelatedInner</code>.
     * @alias module:model/TopicSearchResultItemRelatedInner
     */
    constructor() { 
        
        TopicSearchResultItemRelatedInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TopicSearchResultItemRelatedInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TopicSearchResultItemRelatedInner} obj Optional instance to populate.
     * @return {module:model/TopicSearchResultItemRelatedInner} The populated <code>TopicSearchResultItemRelatedInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopicSearchResultItemRelatedInner();

            if (data.hasOwnProperty('topic_relation')) {
                obj['topic_relation'] = TopicSearchResultItemRelatedInnerTopicRelation.constructFromObject(data['topic_relation']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TopicSearchResultItemRelatedInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TopicSearchResultItemRelatedInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `topic_relation`
        if (data['topic_relation']) { // data not null
          TopicSearchResultItemRelatedInnerTopicRelation.validateJSON(data['topic_relation']);
        }

        return true;
    }


}



/**
 * @member {module:model/TopicSearchResultItemRelatedInnerTopicRelation} topic_relation
 */
TopicSearchResultItemRelatedInner.prototype['topic_relation'] = undefined;






export default TopicSearchResultItemRelatedInner;

