/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnterpriseWebhooks from './EnterpriseWebhooks';
import OrganizationSimpleWebhooks from './OrganizationSimpleWebhooks';
import RepositoryWebhooks from './RepositoryWebhooks';
import SimpleInstallation from './SimpleInstallation';
import SimpleUserWebhooks from './SimpleUserWebhooks';
import WebhooksChanges8 from './WebhooksChanges8';
import WebhooksSponsorship from './WebhooksSponsorship';

/**
 * The WebhookSponsorshipTierChanged model module.
 * @module model/WebhookSponsorshipTierChanged
 * @version 1.1.4
 */
class WebhookSponsorshipTierChanged {
    /**
     * Constructs a new <code>WebhookSponsorshipTierChanged</code>.
     * @alias module:model/WebhookSponsorshipTierChanged
     * @param action {module:model/WebhookSponsorshipTierChanged.ActionEnum} 
     * @param changes {module:model/WebhooksChanges8} 
     * @param sender {module:model/SimpleUserWebhooks} 
     * @param sponsorship {module:model/WebhooksSponsorship} 
     */
    constructor(action, changes, sender, sponsorship) { 
        
        WebhookSponsorshipTierChanged.initialize(this, action, changes, sender, sponsorship);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action, changes, sender, sponsorship) { 
        obj['action'] = action;
        obj['changes'] = changes;
        obj['sender'] = sender;
        obj['sponsorship'] = sponsorship;
    }

    /**
     * Constructs a <code>WebhookSponsorshipTierChanged</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookSponsorshipTierChanged} obj Optional instance to populate.
     * @return {module:model/WebhookSponsorshipTierChanged} The populated <code>WebhookSponsorshipTierChanged</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookSponsorshipTierChanged();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('changes')) {
                obj['changes'] = WebhooksChanges8.constructFromObject(data['changes']);
            }
            if (data.hasOwnProperty('enterprise')) {
                obj['enterprise'] = EnterpriseWebhooks.constructFromObject(data['enterprise']);
            }
            if (data.hasOwnProperty('installation')) {
                obj['installation'] = SimpleInstallation.constructFromObject(data['installation']);
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = OrganizationSimpleWebhooks.constructFromObject(data['organization']);
            }
            if (data.hasOwnProperty('repository')) {
                obj['repository'] = RepositoryWebhooks.constructFromObject(data['repository']);
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = SimpleUserWebhooks.constructFromObject(data['sender']);
            }
            if (data.hasOwnProperty('sponsorship')) {
                obj['sponsorship'] = WebhooksSponsorship.constructFromObject(data['sponsorship']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookSponsorshipTierChanged</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookSponsorshipTierChanged</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookSponsorshipTierChanged.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // validate the optional field `changes`
        if (data['changes']) { // data not null
          WebhooksChanges8.validateJSON(data['changes']);
        }
        // validate the optional field `enterprise`
        if (data['enterprise']) { // data not null
          EnterpriseWebhooks.validateJSON(data['enterprise']);
        }
        // validate the optional field `installation`
        if (data['installation']) { // data not null
          SimpleInstallation.validateJSON(data['installation']);
        }
        // validate the optional field `organization`
        if (data['organization']) { // data not null
          OrganizationSimpleWebhooks.validateJSON(data['organization']);
        }
        // validate the optional field `repository`
        if (data['repository']) { // data not null
          RepositoryWebhooks.validateJSON(data['repository']);
        }
        // validate the optional field `sender`
        if (data['sender']) { // data not null
          SimpleUserWebhooks.validateJSON(data['sender']);
        }
        // validate the optional field `sponsorship`
        if (data['sponsorship']) { // data not null
          WebhooksSponsorship.validateJSON(data['sponsorship']);
        }

        return true;
    }


}

WebhookSponsorshipTierChanged.RequiredProperties = ["action", "changes", "sender", "sponsorship"];

/**
 * @member {module:model/WebhookSponsorshipTierChanged.ActionEnum} action
 */
WebhookSponsorshipTierChanged.prototype['action'] = undefined;

/**
 * @member {module:model/WebhooksChanges8} changes
 */
WebhookSponsorshipTierChanged.prototype['changes'] = undefined;

/**
 * @member {module:model/EnterpriseWebhooks} enterprise
 */
WebhookSponsorshipTierChanged.prototype['enterprise'] = undefined;

/**
 * @member {module:model/SimpleInstallation} installation
 */
WebhookSponsorshipTierChanged.prototype['installation'] = undefined;

/**
 * @member {module:model/OrganizationSimpleWebhooks} organization
 */
WebhookSponsorshipTierChanged.prototype['organization'] = undefined;

/**
 * @member {module:model/RepositoryWebhooks} repository
 */
WebhookSponsorshipTierChanged.prototype['repository'] = undefined;

/**
 * @member {module:model/SimpleUserWebhooks} sender
 */
WebhookSponsorshipTierChanged.prototype['sender'] = undefined;

/**
 * @member {module:model/WebhooksSponsorship} sponsorship
 */
WebhookSponsorshipTierChanged.prototype['sponsorship'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
WebhookSponsorshipTierChanged['ActionEnum'] = {

    /**
     * value: "tier_changed"
     * @const
     */
    "tier_changed": "tier_changed"
};



export default WebhookSponsorshipTierChanged;

