/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User3 from './User3';
import WebhookStatusCommitCommit from './WebhookStatusCommitCommit';
import WebhookStatusCommitParentsInner from './WebhookStatusCommitParentsInner';

/**
 * The WebhookStatusCommit model module.
 * @module model/WebhookStatusCommit
 * @version 1.1.4
 */
class WebhookStatusCommit {
    /**
     * Constructs a new <code>WebhookStatusCommit</code>.
     * @alias module:model/WebhookStatusCommit
     * @param author {module:model/User3} 
     * @param commentsUrl {String} 
     * @param commit {module:model/WebhookStatusCommitCommit} 
     * @param committer {module:model/User3} 
     * @param htmlUrl {String} 
     * @param nodeId {String} 
     * @param parents {Array.<module:model/WebhookStatusCommitParentsInner>} 
     * @param sha {String} 
     * @param url {String} 
     */
    constructor(author, commentsUrl, commit, committer, htmlUrl, nodeId, parents, sha, url) { 
        
        WebhookStatusCommit.initialize(this, author, commentsUrl, commit, committer, htmlUrl, nodeId, parents, sha, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, author, commentsUrl, commit, committer, htmlUrl, nodeId, parents, sha, url) { 
        obj['author'] = author;
        obj['comments_url'] = commentsUrl;
        obj['commit'] = commit;
        obj['committer'] = committer;
        obj['html_url'] = htmlUrl;
        obj['node_id'] = nodeId;
        obj['parents'] = parents;
        obj['sha'] = sha;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>WebhookStatusCommit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookStatusCommit} obj Optional instance to populate.
     * @return {module:model/WebhookStatusCommit} The populated <code>WebhookStatusCommit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookStatusCommit();

            if (data.hasOwnProperty('author')) {
                obj['author'] = User3.constructFromObject(data['author']);
            }
            if (data.hasOwnProperty('comments_url')) {
                obj['comments_url'] = ApiClient.convertToType(data['comments_url'], 'String');
            }
            if (data.hasOwnProperty('commit')) {
                obj['commit'] = WebhookStatusCommitCommit.constructFromObject(data['commit']);
            }
            if (data.hasOwnProperty('committer')) {
                obj['committer'] = User3.constructFromObject(data['committer']);
            }
            if (data.hasOwnProperty('html_url')) {
                obj['html_url'] = ApiClient.convertToType(data['html_url'], 'String');
            }
            if (data.hasOwnProperty('node_id')) {
                obj['node_id'] = ApiClient.convertToType(data['node_id'], 'String');
            }
            if (data.hasOwnProperty('parents')) {
                obj['parents'] = ApiClient.convertToType(data['parents'], [WebhookStatusCommitParentsInner]);
            }
            if (data.hasOwnProperty('sha')) {
                obj['sha'] = ApiClient.convertToType(data['sha'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookStatusCommit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookStatusCommit</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookStatusCommit.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `author`
        if (data['author']) { // data not null
          User3.validateJSON(data['author']);
        }
        // ensure the json data is a string
        if (data['comments_url'] && !(typeof data['comments_url'] === 'string' || data['comments_url'] instanceof String)) {
            throw new Error("Expected the field `comments_url` to be a primitive type in the JSON string but got " + data['comments_url']);
        }
        // validate the optional field `commit`
        if (data['commit']) { // data not null
          WebhookStatusCommitCommit.validateJSON(data['commit']);
        }
        // validate the optional field `committer`
        if (data['committer']) { // data not null
          User3.validateJSON(data['committer']);
        }
        // ensure the json data is a string
        if (data['html_url'] && !(typeof data['html_url'] === 'string' || data['html_url'] instanceof String)) {
            throw new Error("Expected the field `html_url` to be a primitive type in the JSON string but got " + data['html_url']);
        }
        // ensure the json data is a string
        if (data['node_id'] && !(typeof data['node_id'] === 'string' || data['node_id'] instanceof String)) {
            throw new Error("Expected the field `node_id` to be a primitive type in the JSON string but got " + data['node_id']);
        }
        if (data['parents']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['parents'])) {
                throw new Error("Expected the field `parents` to be an array in the JSON data but got " + data['parents']);
            }
            // validate the optional field `parents` (array)
            for (const item of data['parents']) {
                WebhookStatusCommitParentsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['sha'] && !(typeof data['sha'] === 'string' || data['sha'] instanceof String)) {
            throw new Error("Expected the field `sha` to be a primitive type in the JSON string but got " + data['sha']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}

WebhookStatusCommit.RequiredProperties = ["author", "comments_url", "commit", "committer", "html_url", "node_id", "parents", "sha", "url"];

/**
 * @member {module:model/User3} author
 */
WebhookStatusCommit.prototype['author'] = undefined;

/**
 * @member {String} comments_url
 */
WebhookStatusCommit.prototype['comments_url'] = undefined;

/**
 * @member {module:model/WebhookStatusCommitCommit} commit
 */
WebhookStatusCommit.prototype['commit'] = undefined;

/**
 * @member {module:model/User3} committer
 */
WebhookStatusCommit.prototype['committer'] = undefined;

/**
 * @member {String} html_url
 */
WebhookStatusCommit.prototype['html_url'] = undefined;

/**
 * @member {String} node_id
 */
WebhookStatusCommit.prototype['node_id'] = undefined;

/**
 * @member {Array.<module:model/WebhookStatusCommitParentsInner>} parents
 */
WebhookStatusCommit.prototype['parents'] = undefined;

/**
 * @member {String} sha
 */
WebhookStatusCommit.prototype['sha'] = undefined;

/**
 * @member {String} url
 */
WebhookStatusCommit.prototype['url'] = undefined;






export default WebhookStatusCommit;

