/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WebhooksChanges8Tier from './WebhooksChanges8Tier';

/**
 * The WebhooksChanges8 model module.
 * @module model/WebhooksChanges8
 * @version 1.1.4
 */
class WebhooksChanges8 {
    /**
     * Constructs a new <code>WebhooksChanges8</code>.
     * @alias module:model/WebhooksChanges8
     * @param tier {module:model/WebhooksChanges8Tier} 
     */
    constructor(tier) { 
        
        WebhooksChanges8.initialize(this, tier);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tier) { 
        obj['tier'] = tier;
    }

    /**
     * Constructs a <code>WebhooksChanges8</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhooksChanges8} obj Optional instance to populate.
     * @return {module:model/WebhooksChanges8} The populated <code>WebhooksChanges8</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhooksChanges8();

            if (data.hasOwnProperty('tier')) {
                obj['tier'] = WebhooksChanges8Tier.constructFromObject(data['tier']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhooksChanges8</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhooksChanges8</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhooksChanges8.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `tier`
        if (data['tier']) { // data not null
          WebhooksChanges8Tier.validateJSON(data['tier']);
        }

        return true;
    }


}

WebhooksChanges8.RequiredProperties = ["tier"];

/**
 * @member {module:model/WebhooksChanges8Tier} tier
 */
WebhooksChanges8.prototype['tier'] = undefined;






export default WebhooksChanges8;

