/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeploymentWorkflowRun1 from './DeploymentWorkflowRun1';
import EnterpriseWebhooks from './EnterpriseWebhooks';
import OrganizationSimpleWebhooks from './OrganizationSimpleWebhooks';
import RepositoryWebhooks from './RepositoryWebhooks';
import SimpleInstallation from './SimpleInstallation';
import SimpleUserWebhooks from './SimpleUserWebhooks';
import WebhookDeploymentReviewApprovedWorkflowJobRunsInner from './WebhookDeploymentReviewApprovedWorkflowJobRunsInner';
import WebhooksApprover from './WebhooksApprover';
import WebhooksReviewersInner from './WebhooksReviewersInner';
import WebhooksWorkflowJobRun from './WebhooksWorkflowJobRun';

/**
 * The WebhookDeploymentReviewApproved model module.
 * @module model/WebhookDeploymentReviewApproved
 * @version 1.1.4
 */
class WebhookDeploymentReviewApproved {
    /**
     * Constructs a new <code>WebhookDeploymentReviewApproved</code>.
     * @alias module:model/WebhookDeploymentReviewApproved
     * @param action {module:model/WebhookDeploymentReviewApproved.ActionEnum} 
     * @param organization {module:model/OrganizationSimpleWebhooks} 
     * @param repository {module:model/RepositoryWebhooks} 
     * @param sender {module:model/SimpleUserWebhooks} 
     * @param since {String} 
     * @param workflowRun {module:model/DeploymentWorkflowRun1} 
     */
    constructor(action, organization, repository, sender, since, workflowRun) { 
        
        WebhookDeploymentReviewApproved.initialize(this, action, organization, repository, sender, since, workflowRun);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action, organization, repository, sender, since, workflowRun) { 
        obj['action'] = action;
        obj['organization'] = organization;
        obj['repository'] = repository;
        obj['sender'] = sender;
        obj['since'] = since;
        obj['workflow_run'] = workflowRun;
    }

    /**
     * Constructs a <code>WebhookDeploymentReviewApproved</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookDeploymentReviewApproved} obj Optional instance to populate.
     * @return {module:model/WebhookDeploymentReviewApproved} The populated <code>WebhookDeploymentReviewApproved</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookDeploymentReviewApproved();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('approver')) {
                obj['approver'] = WebhooksApprover.constructFromObject(data['approver']);
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('enterprise')) {
                obj['enterprise'] = EnterpriseWebhooks.constructFromObject(data['enterprise']);
            }
            if (data.hasOwnProperty('installation')) {
                obj['installation'] = SimpleInstallation.constructFromObject(data['installation']);
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = OrganizationSimpleWebhooks.constructFromObject(data['organization']);
            }
            if (data.hasOwnProperty('repository')) {
                obj['repository'] = RepositoryWebhooks.constructFromObject(data['repository']);
            }
            if (data.hasOwnProperty('reviewers')) {
                obj['reviewers'] = ApiClient.convertToType(data['reviewers'], [WebhooksReviewersInner]);
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = SimpleUserWebhooks.constructFromObject(data['sender']);
            }
            if (data.hasOwnProperty('since')) {
                obj['since'] = ApiClient.convertToType(data['since'], 'String');
            }
            if (data.hasOwnProperty('workflow_job_run')) {
                obj['workflow_job_run'] = WebhooksWorkflowJobRun.constructFromObject(data['workflow_job_run']);
            }
            if (data.hasOwnProperty('workflow_job_runs')) {
                obj['workflow_job_runs'] = ApiClient.convertToType(data['workflow_job_runs'], [WebhookDeploymentReviewApprovedWorkflowJobRunsInner]);
            }
            if (data.hasOwnProperty('workflow_run')) {
                obj['workflow_run'] = DeploymentWorkflowRun1.constructFromObject(data['workflow_run']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookDeploymentReviewApproved</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookDeploymentReviewApproved</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookDeploymentReviewApproved.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // validate the optional field `approver`
        if (data['approver']) { // data not null
          WebhooksApprover.validateJSON(data['approver']);
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }
        // validate the optional field `enterprise`
        if (data['enterprise']) { // data not null
          EnterpriseWebhooks.validateJSON(data['enterprise']);
        }
        // validate the optional field `installation`
        if (data['installation']) { // data not null
          SimpleInstallation.validateJSON(data['installation']);
        }
        // validate the optional field `organization`
        if (data['organization']) { // data not null
          OrganizationSimpleWebhooks.validateJSON(data['organization']);
        }
        // validate the optional field `repository`
        if (data['repository']) { // data not null
          RepositoryWebhooks.validateJSON(data['repository']);
        }
        if (data['reviewers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['reviewers'])) {
                throw new Error("Expected the field `reviewers` to be an array in the JSON data but got " + data['reviewers']);
            }
            // validate the optional field `reviewers` (array)
            for (const item of data['reviewers']) {
                WebhooksReviewersInner.validateJSON(item);
            };
        }
        // validate the optional field `sender`
        if (data['sender']) { // data not null
          SimpleUserWebhooks.validateJSON(data['sender']);
        }
        // ensure the json data is a string
        if (data['since'] && !(typeof data['since'] === 'string' || data['since'] instanceof String)) {
            throw new Error("Expected the field `since` to be a primitive type in the JSON string but got " + data['since']);
        }
        // validate the optional field `workflow_job_run`
        if (data['workflow_job_run']) { // data not null
          WebhooksWorkflowJobRun.validateJSON(data['workflow_job_run']);
        }
        if (data['workflow_job_runs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['workflow_job_runs'])) {
                throw new Error("Expected the field `workflow_job_runs` to be an array in the JSON data but got " + data['workflow_job_runs']);
            }
            // validate the optional field `workflow_job_runs` (array)
            for (const item of data['workflow_job_runs']) {
                WebhookDeploymentReviewApprovedWorkflowJobRunsInner.validateJSON(item);
            };
        }
        // validate the optional field `workflow_run`
        if (data['workflow_run']) { // data not null
          DeploymentWorkflowRun1.validateJSON(data['workflow_run']);
        }

        return true;
    }


}

WebhookDeploymentReviewApproved.RequiredProperties = ["action", "organization", "repository", "sender", "since", "workflow_run"];

/**
 * @member {module:model/WebhookDeploymentReviewApproved.ActionEnum} action
 */
WebhookDeploymentReviewApproved.prototype['action'] = undefined;

/**
 * @member {module:model/WebhooksApprover} approver
 */
WebhookDeploymentReviewApproved.prototype['approver'] = undefined;

/**
 * @member {String} comment
 */
WebhookDeploymentReviewApproved.prototype['comment'] = undefined;

/**
 * @member {module:model/EnterpriseWebhooks} enterprise
 */
WebhookDeploymentReviewApproved.prototype['enterprise'] = undefined;

/**
 * @member {module:model/SimpleInstallation} installation
 */
WebhookDeploymentReviewApproved.prototype['installation'] = undefined;

/**
 * @member {module:model/OrganizationSimpleWebhooks} organization
 */
WebhookDeploymentReviewApproved.prototype['organization'] = undefined;

/**
 * @member {module:model/RepositoryWebhooks} repository
 */
WebhookDeploymentReviewApproved.prototype['repository'] = undefined;

/**
 * @member {Array.<module:model/WebhooksReviewersInner>} reviewers
 */
WebhookDeploymentReviewApproved.prototype['reviewers'] = undefined;

/**
 * @member {module:model/SimpleUserWebhooks} sender
 */
WebhookDeploymentReviewApproved.prototype['sender'] = undefined;

/**
 * @member {String} since
 */
WebhookDeploymentReviewApproved.prototype['since'] = undefined;

/**
 * @member {module:model/WebhooksWorkflowJobRun} workflow_job_run
 */
WebhookDeploymentReviewApproved.prototype['workflow_job_run'] = undefined;

/**
 * @member {Array.<module:model/WebhookDeploymentReviewApprovedWorkflowJobRunsInner>} workflow_job_runs
 */
WebhookDeploymentReviewApproved.prototype['workflow_job_runs'] = undefined;

/**
 * @member {module:model/DeploymentWorkflowRun1} workflow_run
 */
WebhookDeploymentReviewApproved.prototype['workflow_run'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
WebhookDeploymentReviewApproved['ActionEnum'] = {

    /**
     * value: "approved"
     * @const
     */
    "approved": "approved"
};



export default WebhookDeploymentReviewApproved;

