/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WebhookStatusCommitCommitAuthor model module.
 * @module model/WebhookStatusCommitCommitAuthor
 * @version 1.1.4
 */
class WebhookStatusCommitCommitAuthor {
    /**
     * Constructs a new <code>WebhookStatusCommitCommitAuthor</code>.
     * @alias module:model/WebhookStatusCommitCommitAuthor
     * @param date {String} 
     * @param email {String} 
     * @param name {String} 
     */
    constructor(date, email, name) { 
        
        WebhookStatusCommitCommitAuthor.initialize(this, date, email, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, email, name) { 
        obj['date'] = date;
        obj['email'] = email;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>WebhookStatusCommitCommitAuthor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookStatusCommitCommitAuthor} obj Optional instance to populate.
     * @return {module:model/WebhookStatusCommitCommitAuthor} The populated <code>WebhookStatusCommitCommitAuthor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookStatusCommitCommitAuthor();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookStatusCommitCommitAuthor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookStatusCommitCommitAuthor</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookStatusCommitCommitAuthor.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

WebhookStatusCommitCommitAuthor.RequiredProperties = ["date", "email", "name"];

/**
 * @member {String} date
 */
WebhookStatusCommitCommitAuthor.prototype['date'] = undefined;

/**
 * @member {String} email
 */
WebhookStatusCommitCommitAuthor.prototype['email'] = undefined;

/**
 * @member {String} name
 */
WebhookStatusCommitCommitAuthor.prototype['name'] = undefined;

/**
 * @member {String} username
 */
WebhookStatusCommitCommitAuthor.prototype['username'] = undefined;






export default WebhookStatusCommitCommitAuthor;

