/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnterpriseWebhooks from './EnterpriseWebhooks';
import Installation from './Installation';
import OrganizationSimpleWebhooks from './OrganizationSimpleWebhooks';
import RepositoryWebhooks from './RepositoryWebhooks';
import SimpleUserWebhooks from './SimpleUserWebhooks';
import WebhookInstallationRepositoriesAddedRepositoriesRemovedInner from './WebhookInstallationRepositoriesAddedRepositoriesRemovedInner';
import WebhooksRepositoriesInner from './WebhooksRepositoriesInner';
import WebhooksRepositorySelection from './WebhooksRepositorySelection';
import WebhooksUser from './WebhooksUser';

/**
 * The WebhookInstallationRepositoriesAdded model module.
 * @module model/WebhookInstallationRepositoriesAdded
 * @version 1.1.4
 */
class WebhookInstallationRepositoriesAdded {
    /**
     * Constructs a new <code>WebhookInstallationRepositoriesAdded</code>.
     * @alias module:model/WebhookInstallationRepositoriesAdded
     * @param action {module:model/WebhookInstallationRepositoriesAdded.ActionEnum} 
     * @param installation {module:model/Installation} 
     * @param repositoriesAdded {Array.<module:model/WebhooksRepositoriesInner>} An array of repository objects, which were added to the installation.
     * @param repositoriesRemoved {Array.<module:model/WebhookInstallationRepositoriesAddedRepositoriesRemovedInner>} An array of repository objects, which were removed from the installation.
     * @param repositorySelection {module:model/WebhooksRepositorySelection} 
     * @param requester {module:model/WebhooksUser} 
     * @param sender {module:model/SimpleUserWebhooks} 
     */
    constructor(action, installation, repositoriesAdded, repositoriesRemoved, repositorySelection, requester, sender) { 
        
        WebhookInstallationRepositoriesAdded.initialize(this, action, installation, repositoriesAdded, repositoriesRemoved, repositorySelection, requester, sender);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action, installation, repositoriesAdded, repositoriesRemoved, repositorySelection, requester, sender) { 
        obj['action'] = action;
        obj['installation'] = installation;
        obj['repositories_added'] = repositoriesAdded;
        obj['repositories_removed'] = repositoriesRemoved;
        obj['repository_selection'] = repositorySelection;
        obj['requester'] = requester;
        obj['sender'] = sender;
    }

    /**
     * Constructs a <code>WebhookInstallationRepositoriesAdded</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookInstallationRepositoriesAdded} obj Optional instance to populate.
     * @return {module:model/WebhookInstallationRepositoriesAdded} The populated <code>WebhookInstallationRepositoriesAdded</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookInstallationRepositoriesAdded();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('enterprise')) {
                obj['enterprise'] = EnterpriseWebhooks.constructFromObject(data['enterprise']);
            }
            if (data.hasOwnProperty('installation')) {
                obj['installation'] = Installation.constructFromObject(data['installation']);
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = OrganizationSimpleWebhooks.constructFromObject(data['organization']);
            }
            if (data.hasOwnProperty('repositories_added')) {
                obj['repositories_added'] = ApiClient.convertToType(data['repositories_added'], [WebhooksRepositoriesInner]);
            }
            if (data.hasOwnProperty('repositories_removed')) {
                obj['repositories_removed'] = ApiClient.convertToType(data['repositories_removed'], [WebhookInstallationRepositoriesAddedRepositoriesRemovedInner]);
            }
            if (data.hasOwnProperty('repository')) {
                obj['repository'] = RepositoryWebhooks.constructFromObject(data['repository']);
            }
            if (data.hasOwnProperty('repository_selection')) {
                obj['repository_selection'] = WebhooksRepositorySelection.constructFromObject(data['repository_selection']);
            }
            if (data.hasOwnProperty('requester')) {
                obj['requester'] = WebhooksUser.constructFromObject(data['requester']);
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = SimpleUserWebhooks.constructFromObject(data['sender']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookInstallationRepositoriesAdded</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookInstallationRepositoriesAdded</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookInstallationRepositoriesAdded.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // validate the optional field `enterprise`
        if (data['enterprise']) { // data not null
          EnterpriseWebhooks.validateJSON(data['enterprise']);
        }
        // validate the optional field `installation`
        if (data['installation']) { // data not null
          Installation.validateJSON(data['installation']);
        }
        // validate the optional field `organization`
        if (data['organization']) { // data not null
          OrganizationSimpleWebhooks.validateJSON(data['organization']);
        }
        if (data['repositories_added']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['repositories_added'])) {
                throw new Error("Expected the field `repositories_added` to be an array in the JSON data but got " + data['repositories_added']);
            }
            // validate the optional field `repositories_added` (array)
            for (const item of data['repositories_added']) {
                WebhooksRepositoriesInner.validateJSON(item);
            };
        }
        if (data['repositories_removed']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['repositories_removed'])) {
                throw new Error("Expected the field `repositories_removed` to be an array in the JSON data but got " + data['repositories_removed']);
            }
            // validate the optional field `repositories_removed` (array)
            for (const item of data['repositories_removed']) {
                WebhookInstallationRepositoriesAddedRepositoriesRemovedInner.validateJSON(item);
            };
        }
        // validate the optional field `repository`
        if (data['repository']) { // data not null
          RepositoryWebhooks.validateJSON(data['repository']);
        }
        // validate the optional field `requester`
        if (data['requester']) { // data not null
          WebhooksUser.validateJSON(data['requester']);
        }
        // validate the optional field `sender`
        if (data['sender']) { // data not null
          SimpleUserWebhooks.validateJSON(data['sender']);
        }

        return true;
    }


}

WebhookInstallationRepositoriesAdded.RequiredProperties = ["action", "installation", "repositories_added", "repositories_removed", "repository_selection", "requester", "sender"];

/**
 * @member {module:model/WebhookInstallationRepositoriesAdded.ActionEnum} action
 */
WebhookInstallationRepositoriesAdded.prototype['action'] = undefined;

/**
 * @member {module:model/EnterpriseWebhooks} enterprise
 */
WebhookInstallationRepositoriesAdded.prototype['enterprise'] = undefined;

/**
 * @member {module:model/Installation} installation
 */
WebhookInstallationRepositoriesAdded.prototype['installation'] = undefined;

/**
 * @member {module:model/OrganizationSimpleWebhooks} organization
 */
WebhookInstallationRepositoriesAdded.prototype['organization'] = undefined;

/**
 * An array of repository objects, which were added to the installation.
 * @member {Array.<module:model/WebhooksRepositoriesInner>} repositories_added
 */
WebhookInstallationRepositoriesAdded.prototype['repositories_added'] = undefined;

/**
 * An array of repository objects, which were removed from the installation.
 * @member {Array.<module:model/WebhookInstallationRepositoriesAddedRepositoriesRemovedInner>} repositories_removed
 */
WebhookInstallationRepositoriesAdded.prototype['repositories_removed'] = undefined;

/**
 * @member {module:model/RepositoryWebhooks} repository
 */
WebhookInstallationRepositoriesAdded.prototype['repository'] = undefined;

/**
 * @member {module:model/WebhooksRepositorySelection} repository_selection
 */
WebhookInstallationRepositoriesAdded.prototype['repository_selection'] = undefined;

/**
 * @member {module:model/WebhooksUser} requester
 */
WebhookInstallationRepositoriesAdded.prototype['requester'] = undefined;

/**
 * @member {module:model/SimpleUserWebhooks} sender
 */
WebhookInstallationRepositoriesAdded.prototype['sender'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
WebhookInstallationRepositoriesAdded['ActionEnum'] = {

    /**
     * value: "added"
     * @const
     */
    "added": "added"
};



export default WebhookInstallationRepositoriesAdded;

