/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnterpriseWebhooks from './EnterpriseWebhooks';
import OrganizationSimpleWebhooks from './OrganizationSimpleWebhooks';
import PullRequest7 from './PullRequest7';
import RepositoryWebhooks from './RepositoryWebhooks';
import SimpleInstallation from './SimpleInstallation';
import SimpleUserWebhooks from './SimpleUserWebhooks';
import Team1 from './Team1';

/**
 * The WebhookPullRequestReviewRequestRemovedOneOf1 model module.
 * @module model/WebhookPullRequestReviewRequestRemovedOneOf1
 * @version 1.1.4
 */
class WebhookPullRequestReviewRequestRemovedOneOf1 {
    /**
     * Constructs a new <code>WebhookPullRequestReviewRequestRemovedOneOf1</code>.
     * @alias module:model/WebhookPullRequestReviewRequestRemovedOneOf1
     * @param action {module:model/WebhookPullRequestReviewRequestRemovedOneOf1.ActionEnum} 
     * @param number {Number} The pull request number.
     * @param pullRequest {module:model/PullRequest7} 
     * @param repository {module:model/RepositoryWebhooks} 
     * @param requestedTeam {module:model/Team1} 
     * @param sender {module:model/SimpleUserWebhooks} 
     */
    constructor(action, number, pullRequest, repository, requestedTeam, sender) { 
        
        WebhookPullRequestReviewRequestRemovedOneOf1.initialize(this, action, number, pullRequest, repository, requestedTeam, sender);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action, number, pullRequest, repository, requestedTeam, sender) { 
        obj['action'] = action;
        obj['number'] = number;
        obj['pull_request'] = pullRequest;
        obj['repository'] = repository;
        obj['requested_team'] = requestedTeam;
        obj['sender'] = sender;
    }

    /**
     * Constructs a <code>WebhookPullRequestReviewRequestRemovedOneOf1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookPullRequestReviewRequestRemovedOneOf1} obj Optional instance to populate.
     * @return {module:model/WebhookPullRequestReviewRequestRemovedOneOf1} The populated <code>WebhookPullRequestReviewRequestRemovedOneOf1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookPullRequestReviewRequestRemovedOneOf1();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('enterprise')) {
                obj['enterprise'] = EnterpriseWebhooks.constructFromObject(data['enterprise']);
            }
            if (data.hasOwnProperty('installation')) {
                obj['installation'] = SimpleInstallation.constructFromObject(data['installation']);
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = OrganizationSimpleWebhooks.constructFromObject(data['organization']);
            }
            if (data.hasOwnProperty('pull_request')) {
                obj['pull_request'] = PullRequest7.constructFromObject(data['pull_request']);
            }
            if (data.hasOwnProperty('repository')) {
                obj['repository'] = RepositoryWebhooks.constructFromObject(data['repository']);
            }
            if (data.hasOwnProperty('requested_team')) {
                obj['requested_team'] = Team1.constructFromObject(data['requested_team']);
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = SimpleUserWebhooks.constructFromObject(data['sender']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookPullRequestReviewRequestRemovedOneOf1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookPullRequestReviewRequestRemovedOneOf1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookPullRequestReviewRequestRemovedOneOf1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // validate the optional field `enterprise`
        if (data['enterprise']) { // data not null
          EnterpriseWebhooks.validateJSON(data['enterprise']);
        }
        // validate the optional field `installation`
        if (data['installation']) { // data not null
          SimpleInstallation.validateJSON(data['installation']);
        }
        // validate the optional field `organization`
        if (data['organization']) { // data not null
          OrganizationSimpleWebhooks.validateJSON(data['organization']);
        }
        // validate the optional field `pull_request`
        if (data['pull_request']) { // data not null
          PullRequest7.validateJSON(data['pull_request']);
        }
        // validate the optional field `repository`
        if (data['repository']) { // data not null
          RepositoryWebhooks.validateJSON(data['repository']);
        }
        // validate the optional field `requested_team`
        if (data['requested_team']) { // data not null
          Team1.validateJSON(data['requested_team']);
        }
        // validate the optional field `sender`
        if (data['sender']) { // data not null
          SimpleUserWebhooks.validateJSON(data['sender']);
        }

        return true;
    }


}

WebhookPullRequestReviewRequestRemovedOneOf1.RequiredProperties = ["action", "number", "pull_request", "repository", "requested_team", "sender"];

/**
 * @member {module:model/WebhookPullRequestReviewRequestRemovedOneOf1.ActionEnum} action
 */
WebhookPullRequestReviewRequestRemovedOneOf1.prototype['action'] = undefined;

/**
 * @member {module:model/EnterpriseWebhooks} enterprise
 */
WebhookPullRequestReviewRequestRemovedOneOf1.prototype['enterprise'] = undefined;

/**
 * @member {module:model/SimpleInstallation} installation
 */
WebhookPullRequestReviewRequestRemovedOneOf1.prototype['installation'] = undefined;

/**
 * The pull request number.
 * @member {Number} number
 */
WebhookPullRequestReviewRequestRemovedOneOf1.prototype['number'] = undefined;

/**
 * @member {module:model/OrganizationSimpleWebhooks} organization
 */
WebhookPullRequestReviewRequestRemovedOneOf1.prototype['organization'] = undefined;

/**
 * @member {module:model/PullRequest7} pull_request
 */
WebhookPullRequestReviewRequestRemovedOneOf1.prototype['pull_request'] = undefined;

/**
 * @member {module:model/RepositoryWebhooks} repository
 */
WebhookPullRequestReviewRequestRemovedOneOf1.prototype['repository'] = undefined;

/**
 * @member {module:model/Team1} requested_team
 */
WebhookPullRequestReviewRequestRemovedOneOf1.prototype['requested_team'] = undefined;

/**
 * @member {module:model/SimpleUserWebhooks} sender
 */
WebhookPullRequestReviewRequestRemovedOneOf1.prototype['sender'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
WebhookPullRequestReviewRequestRemovedOneOf1['ActionEnum'] = {

    /**
     * value: "review_request_removed"
     * @const
     */
    "review_request_removed": "review_request_removed"
};



export default WebhookPullRequestReviewRequestRemovedOneOf1;

