/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Discussion from './Discussion';
import OrganizationSimpleWebhooks from './OrganizationSimpleWebhooks';
import RepositoryWebhooks from './RepositoryWebhooks';
import SimpleUserWebhooks from './SimpleUserWebhooks';
import WebhooksAnswer from './WebhooksAnswer';

/**
 * The WebhookDiscussionUnanswered model module.
 * @module model/WebhookDiscussionUnanswered
 * @version 1.1.4
 */
class WebhookDiscussionUnanswered {
    /**
     * Constructs a new <code>WebhookDiscussionUnanswered</code>.
     * @alias module:model/WebhookDiscussionUnanswered
     * @param action {module:model/WebhookDiscussionUnanswered.ActionEnum} 
     * @param discussion {module:model/Discussion} 
     * @param oldAnswer {module:model/WebhooksAnswer} 
     * @param repository {module:model/RepositoryWebhooks} 
     */
    constructor(action, discussion, oldAnswer, repository) { 
        
        WebhookDiscussionUnanswered.initialize(this, action, discussion, oldAnswer, repository);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action, discussion, oldAnswer, repository) { 
        obj['action'] = action;
        obj['discussion'] = discussion;
        obj['old_answer'] = oldAnswer;
        obj['repository'] = repository;
    }

    /**
     * Constructs a <code>WebhookDiscussionUnanswered</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookDiscussionUnanswered} obj Optional instance to populate.
     * @return {module:model/WebhookDiscussionUnanswered} The populated <code>WebhookDiscussionUnanswered</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookDiscussionUnanswered();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('discussion')) {
                obj['discussion'] = Discussion.constructFromObject(data['discussion']);
            }
            if (data.hasOwnProperty('old_answer')) {
                obj['old_answer'] = WebhooksAnswer.constructFromObject(data['old_answer']);
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = OrganizationSimpleWebhooks.constructFromObject(data['organization']);
            }
            if (data.hasOwnProperty('repository')) {
                obj['repository'] = RepositoryWebhooks.constructFromObject(data['repository']);
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = SimpleUserWebhooks.constructFromObject(data['sender']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookDiscussionUnanswered</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookDiscussionUnanswered</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookDiscussionUnanswered.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // validate the optional field `discussion`
        if (data['discussion']) { // data not null
          Discussion.validateJSON(data['discussion']);
        }
        // validate the optional field `old_answer`
        if (data['old_answer']) { // data not null
          WebhooksAnswer.validateJSON(data['old_answer']);
        }
        // validate the optional field `organization`
        if (data['organization']) { // data not null
          OrganizationSimpleWebhooks.validateJSON(data['organization']);
        }
        // validate the optional field `repository`
        if (data['repository']) { // data not null
          RepositoryWebhooks.validateJSON(data['repository']);
        }
        // validate the optional field `sender`
        if (data['sender']) { // data not null
          SimpleUserWebhooks.validateJSON(data['sender']);
        }

        return true;
    }


}

WebhookDiscussionUnanswered.RequiredProperties = ["action", "discussion", "old_answer", "repository"];

/**
 * @member {module:model/WebhookDiscussionUnanswered.ActionEnum} action
 */
WebhookDiscussionUnanswered.prototype['action'] = undefined;

/**
 * @member {module:model/Discussion} discussion
 */
WebhookDiscussionUnanswered.prototype['discussion'] = undefined;

/**
 * @member {module:model/WebhooksAnswer} old_answer
 */
WebhookDiscussionUnanswered.prototype['old_answer'] = undefined;

/**
 * @member {module:model/OrganizationSimpleWebhooks} organization
 */
WebhookDiscussionUnanswered.prototype['organization'] = undefined;

/**
 * @member {module:model/RepositoryWebhooks} repository
 */
WebhookDiscussionUnanswered.prototype['repository'] = undefined;

/**
 * @member {module:model/SimpleUserWebhooks} sender
 */
WebhookDiscussionUnanswered.prototype['sender'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
WebhookDiscussionUnanswered['ActionEnum'] = {

    /**
     * value: "unanswered"
     * @const
     */
    "unanswered": "unanswered"
};



export default WebhookDiscussionUnanswered;

