/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeploymentWorkflowRun3 from './DeploymentWorkflowRun3';
import EnterpriseWebhooks from './EnterpriseWebhooks';
import OrganizationSimpleWebhooks from './OrganizationSimpleWebhooks';
import RepositoryWebhooks from './RepositoryWebhooks';
import SimpleInstallation from './SimpleInstallation';
import SimpleUserWebhooks from './SimpleUserWebhooks';
import WebhookDeploymentReviewRequestedReviewersInner from './WebhookDeploymentReviewRequestedReviewersInner';
import WebhookDeploymentReviewRequestedWorkflowJobRun from './WebhookDeploymentReviewRequestedWorkflowJobRun';
import WebhooksUser from './WebhooksUser';

/**
 * The WebhookDeploymentReviewRequested model module.
 * @module model/WebhookDeploymentReviewRequested
 * @version 1.1.4
 */
class WebhookDeploymentReviewRequested {
    /**
     * Constructs a new <code>WebhookDeploymentReviewRequested</code>.
     * @alias module:model/WebhookDeploymentReviewRequested
     * @param action {module:model/WebhookDeploymentReviewRequested.ActionEnum} 
     * @param environment {String} 
     * @param organization {module:model/OrganizationSimpleWebhooks} 
     * @param repository {module:model/RepositoryWebhooks} 
     * @param requestor {module:model/WebhooksUser} 
     * @param reviewers {Array.<module:model/WebhookDeploymentReviewRequestedReviewersInner>} 
     * @param sender {module:model/SimpleUserWebhooks} 
     * @param since {String} 
     * @param workflowJobRun {module:model/WebhookDeploymentReviewRequestedWorkflowJobRun} 
     * @param workflowRun {module:model/DeploymentWorkflowRun3} 
     */
    constructor(action, environment, organization, repository, requestor, reviewers, sender, since, workflowJobRun, workflowRun) { 
        
        WebhookDeploymentReviewRequested.initialize(this, action, environment, organization, repository, requestor, reviewers, sender, since, workflowJobRun, workflowRun);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action, environment, organization, repository, requestor, reviewers, sender, since, workflowJobRun, workflowRun) { 
        obj['action'] = action;
        obj['environment'] = environment;
        obj['organization'] = organization;
        obj['repository'] = repository;
        obj['requestor'] = requestor;
        obj['reviewers'] = reviewers;
        obj['sender'] = sender;
        obj['since'] = since;
        obj['workflow_job_run'] = workflowJobRun;
        obj['workflow_run'] = workflowRun;
    }

    /**
     * Constructs a <code>WebhookDeploymentReviewRequested</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookDeploymentReviewRequested} obj Optional instance to populate.
     * @return {module:model/WebhookDeploymentReviewRequested} The populated <code>WebhookDeploymentReviewRequested</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookDeploymentReviewRequested();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('enterprise')) {
                obj['enterprise'] = EnterpriseWebhooks.constructFromObject(data['enterprise']);
            }
            if (data.hasOwnProperty('environment')) {
                obj['environment'] = ApiClient.convertToType(data['environment'], 'String');
            }
            if (data.hasOwnProperty('installation')) {
                obj['installation'] = SimpleInstallation.constructFromObject(data['installation']);
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = OrganizationSimpleWebhooks.constructFromObject(data['organization']);
            }
            if (data.hasOwnProperty('repository')) {
                obj['repository'] = RepositoryWebhooks.constructFromObject(data['repository']);
            }
            if (data.hasOwnProperty('requestor')) {
                obj['requestor'] = WebhooksUser.constructFromObject(data['requestor']);
            }
            if (data.hasOwnProperty('reviewers')) {
                obj['reviewers'] = ApiClient.convertToType(data['reviewers'], [WebhookDeploymentReviewRequestedReviewersInner]);
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = SimpleUserWebhooks.constructFromObject(data['sender']);
            }
            if (data.hasOwnProperty('since')) {
                obj['since'] = ApiClient.convertToType(data['since'], 'String');
            }
            if (data.hasOwnProperty('workflow_job_run')) {
                obj['workflow_job_run'] = WebhookDeploymentReviewRequestedWorkflowJobRun.constructFromObject(data['workflow_job_run']);
            }
            if (data.hasOwnProperty('workflow_run')) {
                obj['workflow_run'] = DeploymentWorkflowRun3.constructFromObject(data['workflow_run']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookDeploymentReviewRequested</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookDeploymentReviewRequested</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookDeploymentReviewRequested.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // validate the optional field `enterprise`
        if (data['enterprise']) { // data not null
          EnterpriseWebhooks.validateJSON(data['enterprise']);
        }
        // ensure the json data is a string
        if (data['environment'] && !(typeof data['environment'] === 'string' || data['environment'] instanceof String)) {
            throw new Error("Expected the field `environment` to be a primitive type in the JSON string but got " + data['environment']);
        }
        // validate the optional field `installation`
        if (data['installation']) { // data not null
          SimpleInstallation.validateJSON(data['installation']);
        }
        // validate the optional field `organization`
        if (data['organization']) { // data not null
          OrganizationSimpleWebhooks.validateJSON(data['organization']);
        }
        // validate the optional field `repository`
        if (data['repository']) { // data not null
          RepositoryWebhooks.validateJSON(data['repository']);
        }
        // validate the optional field `requestor`
        if (data['requestor']) { // data not null
          WebhooksUser.validateJSON(data['requestor']);
        }
        if (data['reviewers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['reviewers'])) {
                throw new Error("Expected the field `reviewers` to be an array in the JSON data but got " + data['reviewers']);
            }
            // validate the optional field `reviewers` (array)
            for (const item of data['reviewers']) {
                WebhookDeploymentReviewRequestedReviewersInner.validateJSON(item);
            };
        }
        // validate the optional field `sender`
        if (data['sender']) { // data not null
          SimpleUserWebhooks.validateJSON(data['sender']);
        }
        // ensure the json data is a string
        if (data['since'] && !(typeof data['since'] === 'string' || data['since'] instanceof String)) {
            throw new Error("Expected the field `since` to be a primitive type in the JSON string but got " + data['since']);
        }
        // validate the optional field `workflow_job_run`
        if (data['workflow_job_run']) { // data not null
          WebhookDeploymentReviewRequestedWorkflowJobRun.validateJSON(data['workflow_job_run']);
        }
        // validate the optional field `workflow_run`
        if (data['workflow_run']) { // data not null
          DeploymentWorkflowRun3.validateJSON(data['workflow_run']);
        }

        return true;
    }


}

WebhookDeploymentReviewRequested.RequiredProperties = ["action", "environment", "organization", "repository", "requestor", "reviewers", "sender", "since", "workflow_job_run", "workflow_run"];

/**
 * @member {module:model/WebhookDeploymentReviewRequested.ActionEnum} action
 */
WebhookDeploymentReviewRequested.prototype['action'] = undefined;

/**
 * @member {module:model/EnterpriseWebhooks} enterprise
 */
WebhookDeploymentReviewRequested.prototype['enterprise'] = undefined;

/**
 * @member {String} environment
 */
WebhookDeploymentReviewRequested.prototype['environment'] = undefined;

/**
 * @member {module:model/SimpleInstallation} installation
 */
WebhookDeploymentReviewRequested.prototype['installation'] = undefined;

/**
 * @member {module:model/OrganizationSimpleWebhooks} organization
 */
WebhookDeploymentReviewRequested.prototype['organization'] = undefined;

/**
 * @member {module:model/RepositoryWebhooks} repository
 */
WebhookDeploymentReviewRequested.prototype['repository'] = undefined;

/**
 * @member {module:model/WebhooksUser} requestor
 */
WebhookDeploymentReviewRequested.prototype['requestor'] = undefined;

/**
 * @member {Array.<module:model/WebhookDeploymentReviewRequestedReviewersInner>} reviewers
 */
WebhookDeploymentReviewRequested.prototype['reviewers'] = undefined;

/**
 * @member {module:model/SimpleUserWebhooks} sender
 */
WebhookDeploymentReviewRequested.prototype['sender'] = undefined;

/**
 * @member {String} since
 */
WebhookDeploymentReviewRequested.prototype['since'] = undefined;

/**
 * @member {module:model/WebhookDeploymentReviewRequestedWorkflowJobRun} workflow_job_run
 */
WebhookDeploymentReviewRequested.prototype['workflow_job_run'] = undefined;

/**
 * @member {module:model/DeploymentWorkflowRun3} workflow_run
 */
WebhookDeploymentReviewRequested.prototype['workflow_run'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
WebhookDeploymentReviewRequested['ActionEnum'] = {

    /**
     * value: "requested"
     * @const
     */
    "requested": "requested"
};



export default WebhookDeploymentReviewRequested;

